=== didier31/molecule/molecule/menu.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:menu="http:///menu.ecore" xmlns:menu.item="http:///menu/item.ecore" xmlns:org.eclipse.uml2._2._0._0.uml="http://www.eclipse.org/uml2/2.0.0/UML" xmlns:xsd="http://www.w3.org/2001/XMLSchema" ecore:nsPrefix="menu" ecore:package="menu" org.eclipse.uml2._2._0._0.uml:originalName="Menu" targetNamespace="http:///menu.ecore">
  <xsd:import namespace="http:///menu/item.ecore" schemaLocation="menu.item.xsd"/>
  <xsd:element ecore:ignore="true" name="Menu" type="menu:Menu"/>
  <xsd:complexType name="Menu">
    <xsd:sequence>
      <xsd:element ecore:ordered="false" ecore:resolveProxies="true" maxOccurs="unbounded" minOccurs="0" name="item" type="menu.item:Item"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== didier31/molecule/molecule/Menu extension.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu:Menu xmlns:menu="http:///menu.ecore" xmlns:menu.item="http:///menu/item.ecore" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http:///menu.ecore menu.xsd ">
	<item label="File" id="file">
		<menu>
			<item label="New..." id="idvalue0"></item>
			<item label="Load" id="load"></item>
			<item label="Save" id="save"></item>
			<item label="Exit" id="exit"></item></menu></item>
	<item label="Edit" id="edit"></item></menu:Menu>
